server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    username: root

mybatis:
  type-aliases-package: com.everyweek.ssm
  mapper-locations: classpath:mapper/*.xml
